package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author alumno
 */
public class AlbumJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlbumJDialog.class.getName());

    /**
     * Creates new form AlbumJDialog
     */
    public AlbumJDialog(MainJFrame parent, boolean modal) throws SQLException, IOException {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        this.cancionesTable.getTableHeader().setBackground(Color.black);
        this.cancionesTable.getTableHeader().setForeground(Color.white);
        this.cancionesTable.getTableHeader().setFont(new Font("Arial Black",Font.BOLD,14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cancionesTable = new javax.swing.JTable();
        imagenLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        pupurriLabel = new javax.swing.JLabel();
        albumLabel = new javax.swing.JLabel();
        reproducirLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancionesTable.setBackground(new java.awt.Color(153, 255, 153));
        cancionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imagen", "Album", "Cancion", "Play"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cancionesTable.setRowHeight(75);
        cancionesTable.setShowGrid(true);
        jScrollPane1.setViewportView(cancionesTable);

        imagenLabel.setText("");

        nombreLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("");

        pupurriLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pupurriLabel.setForeground(new java.awt.Color(255, 255, 255));
        pupurriLabel.setText("");

        albumLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        albumLabel.setForeground(new java.awt.Color(255, 255, 255));
        albumLabel.setText("");

        reproducirLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        reproducirLabel.setForeground(new java.awt.Color(255, 255, 255));
        reproducirLabel.setText("");

        addButton.setText("Añadir Cancion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(albumLabel)
                            .addComponent(nombreLabel)
                            .addComponent(pupurriLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reproducirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(albumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreLabel)
                        .addGap(23, 23, 23))
                    .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(pupurriLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reproducirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void addActionListenerAddButton(ActionListener al){
        this.addButton.addActionListener(al);
    }
    
    public void setStatusAddButton(boolean status){
        this.addButton.setVisible(status);
    }

    public JTable getCancionesTable() {
        return cancionesTable;
    }

    public JLabel getImagenLabel() {
        return imagenLabel;
    }

    public JLabel getNombreLabel() {
        return nombreLabel;
    }

    public JLabel getPupurriLabel() {
        return pupurriLabel;
    }

    public JLabel getAlbumLabel() {
        return albumLabel;
    }
    
    public void addCancionesTableMouseListener(MouseListener ml){
        this.cancionesTable.addMouseListener(ml);
    }
    
    public void setReproducirLabel(String text){
        this.reproducirLabel.setText(text);
    }
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel albumLabel;
    private javax.swing.JTable cancionesTable;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel pupurriLabel;
    private javax.swing.JLabel reproducirLabel;
    // End of variables declaration//GEN-END:variables
}
