/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author iagom
 */
public class DatosCancionJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosCancionJDialog.class.getName());

    /**
     * Creates new form DatosCancionJDialog
     */
    public DatosCancionJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public DatosCancionJDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenLabel = new javax.swing.JLabel();
        cancionLabel = new javax.swing.JLabel();
        artistaLabel = new javax.swing.JLabel();
        variosLabel = new javax.swing.JLabel();
        reproduccionesLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        ImagenLabel.setText("");

        cancionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancionLabel.setForeground(new java.awt.Color(255, 255, 255));
        cancionLabel.setText("");

        artistaLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        artistaLabel.setForeground(new java.awt.Color(255, 255, 255));
        artistaLabel.setText("");

        variosLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        variosLabel.setForeground(new java.awt.Color(255, 255, 255));
        variosLabel.setText("");

        reproduccionesLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reproduccionesLabel.setForeground(new java.awt.Color(255, 255, 255));
        reproduccionesLabel.setText("");

        deleteButton.setText("Borrar Canción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ImagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reproduccionesLabel)
                    .addComponent(cancionLabel)
                    .addComponent(artistaLabel)
                    .addComponent(variosLabel))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(artistaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(variosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reproduccionesLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addDeleteButtonActionListener(ActionListener al){
        this.deleteButton.addActionListener(al);
    }
    
    public void setDeleteButtonStatus(boolean status){
        this.deleteButton.setVisible(status);
    }
    
    public void setIconImagenLabel(String url) throws IOException{
        File imagen = new File(url);
        Image image = ImageIO.read(imagen);
        Image imagenRedimensionada = image.getScaledInstance(75, 75, Image.SCALE_SMOOTH);
        ImagenLabel.setIcon(new ImageIcon(imagenRedimensionada));
    }
    
    public String getTextCancionLabel(){
        return cancionLabel.getText();
    }
            
    public void setTextCancionLabel(String nombre){
        cancionLabel.setText(nombre);
    }
        
    public void setTextArtistaLabel(String artista){
        artistaLabel.setText(artista);
    }
    public void setTextVariosLabel(String varios){
        variosLabel.setText(varios);
    }
    public void setTextReproduccionesLabel(double reproducciones){
    
        reproduccionesLabel.setText(String.valueOf(reproducciones/1000000) + "M");
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenLabel;
    private javax.swing.JLabel artistaLabel;
    private javax.swing.JLabel cancionLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel reproduccionesLabel;
    private javax.swing.JLabel variosLabel;
    // End of variables declaration//GEN-END:variables
}
